const clubController = require('../../controllers/businessProcess/clubController')
const {authenticate, isAdmin, isSupperAdmin} = require('../../utils/middlewares')
const router = require('express').Router()
router.get('/clubs',  clubController.getAllClub)
router.get('/clubHistoriques',  clubController.getAllClubHistorique)
router.post('/clubs', authenticate, isAdmin, clubController.addClub)
router.post('/clubHistoriques', authenticate, isAdmin, clubController.addClubHistorique)
router.put('/clubs/:id', authenticate, isAdmin, clubController.updateClub)
router.put('/clubHistoriques/:id', authenticate, isAdmin, clubController.updateClubHistorique)
router.delete('/clubs/:id', authenticate, isAdmin, clubController.deleteClub)
router.delete('/clubHistoriques/:id', authenticate, isAdmin, clubController.deleteClubHistorique)
router.get('/clubs/:id', clubController.getOneClub)
module.exports = router